//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Camping.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PT_Camping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin doit être suprérieure à la date de début.
        /// </summary>
        internal static string beginDate_superior_endDate {
            get {
                return ResourceManager.GetString("beginDate_superior_endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver.
        /// </summary>
        internal static string book {
            get {
                return ResourceManager.GetString("book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservé.
        /// </summary>
        internal static string booked {
            get {
                return ResourceManager.GetString("booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce client est déjà présent dans cette réservation..
        /// </summary>
        internal static string client_already_added {
            get {
                return ResourceManager.GetString("client_already_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client introuvable. Merci de l&apos;écrire sous la forme Nom + Prénom.
        /// </summary>
        internal static string client_not_found {
            get {
                return ResourceManager.GetString("client_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des clients.
        /// </summary>
        internal static string clients_management {
            get {
                return ResourceManager.GetString("clients_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes les valeurs marquées d&apos;une étoile doivent être remplies..
        /// </summary>
        internal static string compulsary_values_exception {
            get {
                return ResourceManager.GetString("compulsary_values_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /5.
        /// </summary>
        internal static string criticality_max {
            get {
                return ResourceManager.GetString("criticality_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la connexion à la base de données.
        /// </summary>
        internal static string database_connection_error {
            get {
                return ResourceManager.GetString("database_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la sauvegarde dans la base de données : 
        ///.
        /// </summary>
        internal static string db_save_error {
            get {
                return ResourceManager.GetString("db_save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé.
        /// </summary>
        internal static string done_issue {
            get {
                return ResourceManager.GetString("done_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des employés.
        /// </summary>
        internal static string employee_management {
            get {
                return ResourceManager.GetString("employee_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;ouverture du fichier, veuillez réessayer..
        /// </summary>
        internal static string error_when_opening_the_file_please_retry {
            get {
                return ResourceManager.GetString("error_when_opening_the_file_please_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier non trouvé ! Veuillez réessayer..
        /// </summary>
        internal static string file_not_found_please_retry {
            get {
                return ResourceManager.GetString("file_not_found_please_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libre.
        /// </summary>
        internal static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string hash_symbol {
            get {
                return ResourceManager.GetString("hash_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour .
        /// </summary>
        internal static string hello_user {
            get {
                return ResourceManager.GetString("hello_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quantité est trop élévée..
        /// </summary>
        internal static string high_quantity_exception {
            get {
                return ResourceManager.GetString("high_quantity_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_back {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_contact_default {
            get {
                object obj = ResourceManager.GetObject("ic_contact_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete {
            get {
                object obj = ResourceManager.GetObject("ic_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_done {
            get {
                object obj = ResourceManager.GetObject("ic_done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_edit {
            get {
                object obj = ResourceManager.GetObject("ic_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_undo {
            get {
                object obj = ResourceManager.GetObject("ic_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files |*.png; *.jpg; *.bmp.
        /// </summary>
        internal static string images_files_formats {
            get {
                return ResourceManager.GetString("images_files_formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date n&apos;est pas valide. 
        ///Vérifier que la date au format YYYY-MM-DD HH:MM:SS 
        ///et supérieure à la date de l&apos;incident..
        /// </summary>
        internal static string invalid_date_exception {
            get {
                return ResourceManager.GetString("invalid_date_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des incidents.
        /// </summary>
        internal static string issues_management {
            get {
                return ResourceManager.GetString("issues_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun incident ne correspond à ce type pour cette période.
        /// </summary>
        internal static string no_issue_corresponding {
            get {
                return ResourceManager.GetString("no_issue_corresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La quantité doit être positive..
        /// </summary>
        internal static string non_positive_quantity_exception {
            get {
                return ResourceManager.GetString("non_positive_quantity_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non réservable.
        /// </summary>
        internal static string not_bookable {
            get {
                return ResourceManager.GetString("not_bookable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING : This feature is not implemented yet..
        /// </summary>
        internal static string not_implemented_feature {
            get {
                return ResourceManager.GetString("not_implemented_feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le libellé du produit ne peut contenir de valeur numérique..
        /// </summary>
        internal static string novalue_product_name_exception {
            get {
                return ResourceManager.GetString("novalue_product_name_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de produit ne peut être vide.
        /// </summary>
        internal static string null_product_name_exception {
            get {
                return ResourceManager.GetString("null_product_name_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string one_space {
            get {
                return ResourceManager.GetString("one_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string percent_symbol {
            get {
                return ResourceManager.GetString("percent_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone doit être un entier de 10 chiffres.
        /// </summary>
        internal static string phone_char_exception {
            get {
                return ResourceManager.GetString("phone_char_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des stocks.
        /// </summary>
        internal static string product_management {
            get {
                return ResourceManager.GetString("product_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des fournisseurs.
        /// </summary>
        internal static string provider_management {
            get {
                return ResourceManager.GetString("provider_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réservation effectuée !.
        /// </summary>
        internal static string reservation_done {
            get {
                return ResourceManager.GetString("reservation_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La réservation doit contenir au moins un emplacement.
        /// </summary>
        internal static string reservation_need_at_least_1_location {
            get {
                return ResourceManager.GetString("reservation_need_at_least_1_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des réservations de : .
        /// </summary>
        internal static string reservationTitleLabel {
            get {
                return ResourceManager.GetString("reservationTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez une image de fond.
        /// </summary>
        internal static string select_background_image {
            get {
                return ResourceManager.GetString("select_background_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez une image pour le type .
        /// </summary>
        internal static string select_image_for_the_type {
            get {
                return ResourceManager.GetString("select_image_for_the_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des statistiques.
        /// </summary>
        internal static string stats_management {
            get {
                return ResourceManager.GetString("stats_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des stocks.
        /// </summary>
        internal static string stocks_management {
            get {
                return ResourceManager.GetString("stocks_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libérer.
        /// </summary>
        internal static string unbook {
            get {
                return ResourceManager.GetString("unbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site web inconnu.
        /// </summary>
        internal static string unknown_site {
            get {
                return ResourceManager.GetString("unknown_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email n&apos;est pas une adresse mail valide.
        /// </summary>
        internal static string unrecognized_email {
            get {
                return ResourceManager.GetString("unrecognized_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site web n&apos;est pas un site web valide.
        /// </summary>
        internal static string unrecognized_website {
            get {
                return ResourceManager.GetString("unrecognized_website", resourceCulture);
            }
        }
    }
}
