//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Camping.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PT_Camping.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réserver.
        /// </summary>
        internal static string book {
            get {
                return ResourceManager.GetString("book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reservé.
        /// </summary>
        internal static string booked {
            get {
                return ResourceManager.GetString("booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des clients.
        /// </summary>
        internal static string clients_management {
            get {
                return ResourceManager.GetString("clients_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes les valeurs marquées d&apos;une étoile doivent être remplies..
        /// </summary>
        internal static string compulsary_values_exception {
            get {
                return ResourceManager.GetString("compulsary_values_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /5.
        /// </summary>
        internal static string criticality_max {
            get {
                return ResourceManager.GetString("criticality_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la connexion à la base de données.
        /// </summary>
        internal static string database_connection_error {
            get {
                return ResourceManager.GetString("database_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la sauvegarde dans la base de données : 
        ///.
        /// </summary>
        internal static string db_save_error {
            get {
                return ResourceManager.GetString("db_save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cet élément ?.
        /// </summary>
        internal static string delete_item_confirm_message {
            get {
                return ResourceManager.GetString("delete_item_confirm_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès refusé. 
        ///Veuillez contacter votre administrateur..
        /// </summary>
        internal static string denied_access {
            get {
                return ResourceManager.GetString("denied_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminé.
        /// </summary>
        internal static string done_issue {
            get {
                return ResourceManager.GetString("done_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des employés.
        /// </summary>
        internal static string employee_management {
            get {
                return ResourceManager.GetString("employee_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de l&apos;ouverture du fichier, veuillez réessayer..
        /// </summary>
        internal static string error_when_opening_the_file_please_retry {
            get {
                return ResourceManager.GetString("error_when_opening_the_file_please_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier non trouvé ! Veuillez réessayer..
        /// </summary>
        internal static string file_not_found_please_retry {
            get {
                return ResourceManager.GetString("file_not_found_please_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libre.
        /// </summary>
        internal static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #.
        /// </summary>
        internal static string hash_symbol {
            get {
                return ResourceManager.GetString("hash_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour .
        /// </summary>
        internal static string hello_user {
            get {
                return ResourceManager.GetString("hello_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La quantité est trop élévée..
        /// </summary>
        internal static string high_quantity_exception {
            get {
                return ResourceManager.GetString("high_quantity_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_add_a_photo {
            get {
                object obj = ResourceManager.GetObject("ic_add_a_photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_arrow_back {
            get {
                object obj = ResourceManager.GetObject("ic_arrow_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_contact_default {
            get {
                object obj = ResourceManager.GetObject("ic_contact_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_delete {
            get {
                object obj = ResourceManager.GetObject("ic_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_done {
            get {
                object obj = ResourceManager.GetObject("ic_done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_edit {
            get {
                object obj = ResourceManager.GetObject("ic_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_issue_done {
            get {
                object obj = ResourceManager.GetObject("ic_issue_done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_issue_pending {
            get {
                object obj = ResourceManager.GetObject("ic_issue_pending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_stock_empty {
            get {
                object obj = ResourceManager.GetObject("ic_stock_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_stock_low {
            get {
                object obj = ResourceManager.GetObject("ic_stock_low", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ic_undo {
            get {
                object obj = ResourceManager.GetObject("ic_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image Files |*.png; *.jpg; *.bmp.
        /// </summary>
        internal static string images_files_formats {
            get {
                return ResourceManager.GetString("images_files_formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date n&apos;est pas valide. 
        ///Vérifier que la date au format YYYY-MM-DD HH:MM:SS 
        ///et supérieure à la date de l&apos;incident..
        /// </summary>
        internal static string invalid_date_exception {
            get {
                return ResourceManager.GetString("invalid_date_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des incidents.
        /// </summary>
        internal static string issues_management {
            get {
                return ResourceManager.GetString("issues_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun incident ne correspond à ce type pour cette période.
        /// </summary>
        internal static string no_issue_corresponding {
            get {
                return ResourceManager.GetString("no_issue_corresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La quantité doit être positive..
        /// </summary>
        internal static string non_positive_quantity_exception {
            get {
                return ResourceManager.GetString("non_positive_quantity_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non réservable.
        /// </summary>
        internal static string not_bookable {
            get {
                return ResourceManager.GetString("not_bookable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WARNING : This feature is not implemented yet..
        /// </summary>
        internal static string not_implemented_feature {
            get {
                return ResourceManager.GetString("not_implemented_feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le libellé du produit ne peut contenir de valeur numérique..
        /// </summary>
        internal static string novalue_product_name_exception {
            get {
                return ResourceManager.GetString("novalue_product_name_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom de produit ne peut être vide.
        /// </summary>
        internal static string null_product_name_exception {
            get {
                return ResourceManager.GetString("null_product_name_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  .
        /// </summary>
        internal static string one_space {
            get {
                return ResourceManager.GetString("one_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à %.
        /// </summary>
        internal static string percent_symbol {
            get {
                return ResourceManager.GetString("percent_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone doit être un entier de 10 chiffres.
        /// </summary>
        internal static string phone_char_exception {
            get {
                return ResourceManager.GetString("phone_char_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des stocks.
        /// </summary>
        internal static string product_management {
            get {
                return ResourceManager.GetString("product_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des fournisseurs.
        /// </summary>
        internal static string provider_management {
            get {
                return ResourceManager.GetString("provider_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez une image de fond.
        /// </summary>
        internal static string select_background_image {
            get {
                return ResourceManager.GetString("select_background_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez une image pour le type .
        /// </summary>
        internal static string select_image_for_the_type {
            get {
                return ResourceManager.GetString("select_image_for_the_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des statistiques.
        /// </summary>
        internal static string stats_management {
            get {
                return ResourceManager.GetString("stats_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des stocks.
        /// </summary>
        internal static string stocks_management {
            get {
                return ResourceManager.GetString("stocks_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libérer.
        /// </summary>
        internal static string unbook {
            get {
                return ResourceManager.GetString("unbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site web inconnu.
        /// </summary>
        internal static string unknown_site {
            get {
                return ResourceManager.GetString("unknown_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email n&apos;est pas une adresse mail valide.
        /// </summary>
        internal static string unrecognized_email {
            get {
                return ResourceManager.GetString("unrecognized_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site web n&apos;est pas un site web valide.
        /// </summary>
        internal static string unrecognized_website {
            get {
                return ResourceManager.GetString("unrecognized_website", resourceCulture);
            }
        }
    }
}
