//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Camping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public System.DateTime Date_Inscription { get; set; }
        public int Code_Personne { get; set; }
    
        public virtual Personne Personne { get; set; }
    }
}
