//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Camping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public int Code_Personne { get; set; }
        public bool EstLicencie { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Personne Personne { get; set; }
    }
}
