//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Camping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int Code_Facture { get; set; }
        public double Montant { get; set; }
        public Nullable<System.DateTime> Date_Emission { get; set; }
        public int Code_Reservation { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
