//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Camping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int Code_Incident { get; set; }
        public int Code_Emplacement { get; set; }
        public int Code_Type { get; set; }
        public string Description_Incident { get; set; }
        public System.DateTime Date_Incident { get; set; }
        public Nullable<System.DateTime> Date_Resolution { get; set; }
        public int Criticite_Incident { get; set; }
        public string Avancement_Incident { get; set; }
    
        public virtual Emplacement Emplacement { get; set; }
        public virtual Type_Incident Type_Incident { get; set; }
    }
}
