//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_Camping.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Loge = new HashSet<Loge>();
        }
    
        public int Code_Reservation { get; set; }
        public System.DateTime Date_Debut { get; set; }
        public System.DateTime Date_Fin { get; set; }
        public bool Est_Paye { get; set; }
        public int Code_Personne { get; set; }
        public int Code_Facture { get; set; }
    
        public virtual Facture Facture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loge> Loge { get; set; }
        public virtual Personne Personne { get; set; }
    }
}
