//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int Code_Incident { get; set; }
        public int Code_Emplacement { get; set; }
        public int Code_Type { get; set; }
        public string Description_Incident { get; set; }
        public System.DateTime Date_Incident { get; set; }
        public Nullable<System.DateTime> Date_Resolution { get; set; }
        public int Criticite_Incident { get; set; }
        public string Avancement_Incident { get; set; }
    
        public virtual Emplacement Emplacement { get; set; }
        public virtual Type_Incident Type_Incident { get; set; }
    }
}
