//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public byte[] Fond_Image { get; set; }
        public int Code_App { get; set; }
    }
}
