//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PT4_Camping_JJBMREntities : DbContext
    {
        public PT4_Camping_JJBMREntities()
            : base("name=PT4_Camping_JJBMREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_vendu> A_vendu { get; set; }
        public virtual DbSet<App> App { get; set; }
        public virtual DbSet<Caracteristique_Emplacement> Caracteristique_Emplacement { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Droit> Droit { get; set; }
        public virtual DbSet<Emplacement> Emplacement { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Incident> Incident { get; set; }
        public virtual DbSet<Loge> Loge { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Emplacement> Type_Emplacement { get; set; }
        public virtual DbSet<Type_Incident> Type_Incident { get; set; }
    }
}
