//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public int Code_Personne { get; set; }
        public bool EstLicencie { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Personne Personne { get; set; }
    }
}
